### ISSUE TITLE
Syntax for checking if keys are in multidimensional array is not recognized

### ISSUE THREAD

**Issue by Popkornium18** [Beaglefoot/tree-sitter-awk#12]
This is the correct syntax to check whether a sequence of keys is in a multidimensional array:

```
BEGIN {
  array[1,2,3] = 4
  if ((1,2,3) in array) print "(1,2,3) is in array"
  else print "(1,2,3) is not in array"
  if ((2,1,3) in array) print "(2,1,3) is in array"
  else print "(2,1,3) is not in array"
}
```

However, this is parsed as an error by the tree-sitter awk grammar.

This syntax is described in the [Gawk Manual](https://www.gnu.org/software/gawk/manual/html_node/Multidimensional.html).

**Comment by Beaglefoot** [comment]
Good catch!
v0.5.4 fixes it. Thanks for reporting!
