### ISSUE TITLE
function name conflict causing neovim to crash

### ISSUE THREAD

**Issue by Badhi** [Beaglefoot/tree-sitter-awk#7]
For the following awk example, `neovim` editor crashes 

```awk
{
    for (d in k) {
        if ( d == -1 ) continue
        #print
    }
}
```

Steps to recreate:
* Install [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground) in neovim
* Install this awk treesitter parser in nvim-treesitter by adding the following config
```lua
    parser_config.awk = {
        install_info = {
            url = "/home/user/tree-sitter-awk", -- local path or git repo
            files = {"src/parser.c", "src/scanner.c"},
        },
        filetype = "awk", -- if filetype does not match the parser name
    }
```
* open the above awk example and open Playground by entering `:TSPlaygroundToggle`
* the editor will crash

The crash is observed only when used with `neovim`. It does not crash for `tree-sitter parse test.awk`

The **reason for the crash is a function name conflict** since both `neovim` and `src/scanner.c` has a function called `skip_comment`. Which causes the process to choose the neovim's function instead of the awk's one. Refer the stack trace below 

```
#0  skip_comment (line=0x101ba90 "#", process=<optimized out>, include_space=<optimized out>, is_comment=0x23) at neovim/src/nvim/ops.c:3847
#1  0x00007fffee818227 in is_if_else_separator (lexer=0x101ba90) at src/scanner.c:127
#2  0x00007fffee818451 in tree_sitter_awk_external_scanner_scan (payload=0x0, lexer=0x101ba90, valid_symbols=0x7fffeea1c198 <ts_external_scanner_states+8>) at src/scanner.c:235
```

`frame #0` refers to a function owned by neovim which instead should be the `skip_comment` function in the `src/scanner.c`

Will it be possible to add prefixes to the function names to make them unique? That will fix this issue

**Comment by Beaglefoot** [comment]
Thanks, @Badhi.

I can replicate the issue. Fix will be ready in a few moments.
