### ISSUE TITLE
Error in query file "highlights.scm"

### ISSUE THREAD

**Issue by setop** [Beaglefoot/tree-sitter-awk#8]
Hi, 

First of all, thanks for this project. I'm a fan of AWK language and I'm happy it is now part or the tree-sitter ecosystem.

I have an error when using highlight feature:

running `tree-sitter highlight a.awk`, gives:

```
Error in query file "highlights.scm"

Caused by:
    Query error at 10:18. Invalid syntax:
    (func_def name: (* (identifier) @function) @function)
```
I commented out the incriminated lines, as a workaround :

```
;(func_def name: (* (identifier) @function) @function)
;(func_call name: (* (identifier) @function) @function)
```
It works.

But I guess it won't highlight function definitions and calls.

I'm not skilled enough in scheme and tree-sitter highlighting system to fix the issue so I just report, sorry.

## version

```
tree-sitter -V
tree-sitter 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c)
```

**Comment by Beaglefoot** [comment]
Hi @setop

I updated tree-sitter version and highlights.scm. So if you're using master branch, you should be fine now.

Please note that if you're using the latest release (v0.5.1), you should stick to tree-sitter-cli v0.19.2.
